// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_a19MZaRXkGVNdYnp7E1jzGD-ygk1Cs',
    appId: '1:518693681477:web:51873a0e244c6f55f7262c',
    messagingSenderId: '518693681477',
    projectId: 'carquest-af9db',
    authDomain: 'carquest-af9db.firebaseapp.com',
    databaseURL: 'https://carquest-af9db-default-rtdb.firebaseio.com',
    storageBucket: 'carquest-af9db.firebasestorage.app',
    measurementId: 'G-TCC2CJT3LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhbNMlvgTnXJYeEKYA9vmWrjj_LYpRKbI',
    appId: '1:518693681477:android:6c43fc947bb241c5f7262c',
    messagingSenderId: '518693681477',
    projectId: 'carquest-af9db',
    databaseURL: 'https://carquest-af9db-default-rtdb.firebaseio.com',
    storageBucket: 'carquest-af9db.firebasestorage.app',
  );

}